services:
  db:
    image: mysql:8.0
    container_name: itlearning_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: itlearning
    ports:
      - "33066:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  db_data:
